# SPDX-License-Identifier: GPL-3.0-or-later
# Netdata health alarms for lsi-hba-temp.
template: lsi_hba_temp_warning
      on: lsi_hba_temp.temperature
    calc: $this
   every: 10s
    warn: $this >= 65
    crit: $this >= 80
   units: C
    info: LSI/Broadcom HBA controller temperature is high
      to: sysadmin
