# SPDX-License-Identifier: GPL-3.0-or-later
# Netdata health alarms for lsi-hba-temp.
# Warn at >=65C and critical at >=80C for each HBA temperature dimension.

template: lsi_hba_temp_temperature
      on: lsi_hba_temp.temperature
  lookup: average -30s foreach *
   every: 10s
   units: C
    warn: $this >= 65
    crit: $this >= 80
   delay: up 0 down 5m multiplier 1.5 max 1h
    info: LSI/Broadcom HBA controller temperature is high
      to: sysadmin
